In [2]:
import pandas as pd
import numpy as np

PATH = '/home/kai/data/kaggle/homecredit/'

train_df = pd.read_pickle(PATH+'train_merge.pkl')
test_df = pd.read_pickle(PATH+'test_merge.pkl')
print('done')

done

In [3]:
print(train_df.shape,test_df.shape)
sub = 'submission/modify_final_4.csv'
old_merge = pd.read_csv(PATH+sub)
half = old_merge[old_merge['TARGET'] <0.005]
index_half = half.index
test_half = test_df.iloc[index_half]
test_half['TARGET'] = 0
test_df.drop(index_half, inplace = True)
train = pd.concat([train_df,test_half])
print(train.shape,test_df.shape)
train.to_pickle(PATH + 'inter\train_modify_less_1.pkl')
test_df.to_pickle(PATH + 'inter\test_modify_less_1.pkl')

(307511, 899) (48744, 898)

/home/kai/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

(307857, 899) (48398, 898)

In [3]:
# half length: 251 for modify_final_4)

251

In [4]:
other = pd.read_csv(PATH + 'inter/sub_lesspart_1.csv')
sub = pd.concat([half,other],axis = 0)
sub.shape

(48744, 2)

In [5]:
test = pd.read_csv(PATH + 'application_test.csv')

In [6]:
test_id = test[['SK_ID_CURR']]

In [7]:
test_new = test_id.merge(sub, on = 'SK_ID_CURR', how = 'left')

In [8]:
len(test_new[test_new['TARGET']<0.005])

365

In [12]:
test_less_1 = test_new
new = test_less_1

In [13]:
new

       SK_ID_CURR    TARGET
0          100001  0.025603
1          100005  0.113514
2          100013  0.024501
3          100028  0.031941
4          100038  0.151434
5          100042  0.033932
6          100057  0.007071
7          100065  0.031660
8          100066  0.014140
9          100067  0.083319
10         100074  0.052697
11         100090  0.030024
12         100091  0.197542
13         100092  0.037292
14         100106  0.047280
15         100107  0.178128
16         100109  0.056910
17         100117  0.030914
18         100128  0.061903
19         100141  0.037204
20         100150  0.028687
21         100168  0.011659
22         100169  0.032023
23         100170  0.148372
24         100171  0.053991
25         100172  0.107353
26         100184  0.073073
27         100187  0.071811
28         100212  0.025176
29         100222  0.034339
...           ...       ...
48714      455963  0.028269
48715      455965  0.011424
48716      456007  0.238113
48717      456008  0.015693
48718      456009  0.031256
48719      456010  0.101271
48720      456011  0.028394
48721      456013  0.291886
48722      456028  0.139065
48723      456058  0.101992
48724      456111  0.064767
48725      456114  0.109640
48726      456115  0.032126
48727      456116  0.009660
48728      456119  0.010593
48729      456120  0.111538
48730      456122  0.068398
48731      456123  0.027125
48732      456166  0.110791
48733      456167  0.038874
48734      456168  0.035578
48735      456169  0.052519
48736      456170  0.010351
48737      456189  0.149441
48738      456202  0.063739
48739      456221  0.060052
48740      456222  0.063702
48741      456223  0.009816
48742      456224  0.023689
48743      456250  0.260760

[48744 rows x 2 columns]

In [19]:
new['TARGET'] = (test_less_1['TARGET']+old_merge['TARGET'])/2

In [25]:
new.to_csv(PATH+'submission/less_half_1.csv',index = False)

In [22]:
len(new[new['TARGET']>0.5])

214

In [23]:
len(new[new['TARGET']<0.005])

356

In [24]:
new

       SK_ID_CURR    TARGET
0          100001  0.024642
1          100005  0.112734
2          100013  0.025159
3          100028  0.031677
4          100038  0.153629
5          100042  0.034590
6          100057  0.007163
7          100065  0.033375
8          100066  0.014407
9          100067  0.087942
10         100074  0.050149
11         100090  0.027532
12         100091  0.203278
13         100092  0.038438
14         100106  0.046035
15         100107  0.181178
16         100109  0.061545
17         100117  0.029643
18         100128  0.058002
19         100141  0.035862
20         100150  0.027756
21         100168  0.010710
22         100169  0.033943
23         100170  0.150259
24         100171  0.055170
25         100172  0.109790
26         100184  0.072107
27         100187  0.073841
28         100212  0.024464
29         100222  0.033503
...           ...       ...
48714      455963  0.029365
48715      455965  0.011122
48716      456007  0.234001
48717      456008  0.015621
48718      456009  0.030930
48719      456010  0.114803
48720      456011  0.029890
48721      456013  0.290163
48722      456028  0.150993
48723      456058  0.104241
48724      456111  0.063858
48725      456114  0.118465
48726      456115  0.031052
48727      456116  0.009419
48728      456119  0.010528
48729      456120  0.109176
48730      456122  0.069537
48731      456123  0.027215
48732      456166  0.118382
48733      456167  0.039333
48734      456168  0.035333
48735      456169  0.055063
48736      456170  0.010928
48737      456189  0.153460
48738      456202  0.059952
48739      456221  0.064445
48740      456222  0.063959
48741      456223  0.009777
48742      456224  0.022502
48743      456250  0.264818

[48744 rows x 2 columns]