In [2]:
import pandas as pd
import numpy as np

In [3]:
PATH = '/home/kai/data/kaggle/homecredit/'
train = pd.read_csv(PATH + 'application_train.csv')
print('train')
test = pd.read_csv(PATH + 'application_test.csv')
print('test')
bureau = pd.read_csv(PATH + 'bureau.csv')
print('bureau')
prev = pd.read_csv(PATH + 'previous_application.csv')
print('previous')
bb = pd.read_csv(PATH + 'bureau_balance.csv')
print('bureau_balance')
installments_payments = pd.read_csv(PATH + 'installments_payments.csv')
print('installments_payments done')
credit_card_balance = pd.read_csv(PATH + 'credit_card_balance.csv')
# print('credit_card_balance')
POS_CASH_balance = pd.read_csv(PATH + 'POS_CASH_balance.csv')
print('POS_CASH_balance')
credit_card_balance = pd.read_csv(PATH + 'credit_card_balance.csv')
print('credit_card_balance')
previous_application = pd.read_csv(PATH + 'previous_application.csv')
print('previous_application')

train
test
bureau
previous
bureau_balance
installments_payments done
POS_CASH_balance
credit_card_balance
previous_application

In [4]:
print(installments_payments.head())

   SK_ID_PREV  SK_ID_CURR  NUM_INSTALMENT_VERSION  NUM_INSTALMENT_NUMBER  \
0     1054186      161674                     1.0                      6
1     1330831      151639                     0.0                     34
2     2085231      193053                     2.0                      1
3     2452527      199697                     1.0                      3
4     2714724      167756                     1.0                      2

   DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  AMT_INSTALMENT  AMT_PAYMENT
0          -1180.0             -1187.0        6948.360     6948.360
1          -2156.0             -2156.0        1716.525     1716.525
2            -63.0               -63.0       25425.000    25425.000
3          -2418.0             -2426.0       24350.130    24350.130
4          -1383.0             -1366.0        2165.040     2160.585

In [5]:
# set(installments_payments.index.values)
installments_payments['NUM_INSTALMENT_VERSION'].min()

0.0

In [6]:
_df = installments_payments.sort_values(by = ['SK_ID_CURR', 'DAYS_INSTALMENT'], ascending = [True, False])

In [7]:
_df.head(50)

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
2624024,1369693,100001,2.0,4,-1619.0,-1628.0,17397.900,17397.900
3458712,1369693,100001,1.0,3,-1649.0,-1660.0,3951.000,3951.000
2568722,1369693,100001,1.0,2,-1679.0,-1715.0,3951.000,3951.000
1478621,1369693,100001,1.0,1,-1709.0,-1715.0,3951.000,3951.000
3435373,1851984,100001,1.0,4,-2856.0,-2856.0,3980.925,3980.925
3774071,1851984,100001,1.0,3,-2886.0,-2875.0,3982.050,3982.050
1761012,1851984,100001,1.0,2,-2916.0,-2916.0,3982.050,3982.050
442432,1038818,100002,2.0,19,-25.0,-49.0,53093.745,53093.745
1390511,1038818,100002,1.0,18,-55.0,-67.0,9251.775,9251.775
916044,1038818,100002,1.0,17,-85.0,-99.0,9251.775,9251.775
185679,1038818,100002,1.0,16,-115.0,-133.0,9251.775,9251.775
1703436,1038818,100002,1.0,15,-145.0,-160.0,9251.775,9251.775
740300,1038818,100002,1.0,14,-175.0,-194.0,9251.775,9251.775
699804,1038818,100002,1.0,13,-205.0,-224.0,9251.775,9251.775
504426,1038818,100002,1.0,12,-235.0,-250.0,9251.775,9251.775
2785201,1038818,100002,1.0,11,-265.0,-284.0,9251.775,9251.775
2646927,1038818,100002,1.0,10,-295.0,-312.0,9251.775,9251.775
607863,1038818,100002,1.0,9,-325.0,-344.0,9251.775,9251.775
210205,1038818,100002,1.0,8,-355.0,-375.0,9251.775,9251.775
3594829,1038818,100002,1.0,7,-385.0,-412.0,9251.775,9251.775
1807424,1038818,100002,1.0,6,-415.0,-446.0,9251.775,9251.775
2841063,1038818,100002,1.0,5,-445.0,-468.0,9251.775,9251.775
3343696,1038818,100002,1.0,4,-475.0,-498.0,9251.775,9251.775
1675768,1038818,100002,1.0,3,-505.0,-529.0,9251.775,9251.775
2163032,1038818,100002,1.0,2,-535.0,-562.0,9251.775,9251.775
2144879,1038818,100002,1.0,1,-565.0,-587.0,9251.775,9251.775
1179410,1810518,100003,2.0,7,-536.0,-544.0,560835.360,560835.360
3421285,1810518,100003,1.0,6,-566.0,-570.0,98356.995,98356.995
1206007,1810518,100003,1.0,5,-596.0,-600.0,98356.995,98356.995
1687015,1810518,100003,1.0,4,-626.0,-629.0,98356.995,98356.995
2201984,2636178,100003,1.0,6,-647.0,-661.0,64275.615,64275.615
446588,1810518,100003,1.0,3,-656.0,-661.0,98356.995,98356.995
1233145,2636178,100003,1.0,5,-677.0,-690.0,64567.665,64567.665
13709,1810518,100003,1.0,2,-686.0,-690.0,98356.995,98356.995
1868790,2636178,100003,1.0,4,-707.0,-719.0,64567.665,64567.665
2627835,1810518,100003,1.0,1,-716.0,-719.0,98356.995,98356.995
1872725,2636178,100003,1.0,3,-737.0,-746.0,64567.665,64567.665
1923162,2636178,100003,1.0,2,-767.0,-777.0,64567.665,64567.665
1479922,2636178,100003,1.0,1,-797.0,-806.0,64567.665,64567.665
1139956,2396755,100003,1.0,12,-1980.0,-1985.0,6662.970,6662.970
1519746,2396755,100003,1.0,11,-2010.0,-2013.0,6737.310,6737.310
1475983,2396755,100003,1.0,10,-2040.0,-2044.0,6737.310,6737.310
570555,2396755,100003,1.0,9,-2070.0,-2071.0,6737.310,6737.310
2004439,2396755,100003,1.0,8,-2100.0,-2105.0,6737.310,6737.310
1001994,2396755,100003,1.0,7,-2130.0,-2136.0,6737.310,6737.310
3164200,2396755,100003,1.0,6,-2160.0,-2168.0,6737.310,6737.310
620125,2396755,100003,1.0,5,-2190.0,-2199.0,6737.310,6737.310
480811,2396755,100003,1.0,4,-2220.0,-2226.0,6737.310,6737.310
2771895,2396755,100003,1.0,3,-2250.0,-2260.0,6737.310,6737.310
1532400,2396755,100003,1.0,2,-2280.0,-2290.0,6737.310,6737.310

In [8]:
x = _df[_df['DAYS_INSTALMENT'] > -300]

In [9]:
print(x.shape,_df.shape)
print(x.shape[0]/_df.shape[0])

(2828559, 8) (13605401, 8)
0.20789971570848959

In [10]:
set_train = set(train['SK_ID_CURR'])
set_install = set(installments_payments['SK_ID_CURR'])

In [11]:
print(len(set_train-set_install))

15868

In [12]:
len(set_install)

339587

In [13]:
len(set_train)

307511

In [14]:
len(set_install - set_train)

47944

In [15]:
339587 - 307511

32076

In [16]:
len(set_train - set_install)

15868

In [17]:
set_test = set(test['SK_ID_CURR'])

In [53]:
set_union = set_train.union(set_test)

In [54]:
print(set_install - set_union)

set()

# Credit_card

In [55]:
credit_card_balance.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0

In [93]:
_credit = credit_card_balance.sort_values(by = ['SK_ID_CURR', 'MONTHS_BALANCE'], ascending = [True, False])

In [94]:
set(_credit['NAME_CONTRACT_STATUS'])

{'Active',
 'Approved',
 'Completed',
 'Demand',
 'Refused',
 'Sent proposal',
 'Signed'}

In [96]:
x = _credit[_credit['NAME_CONTRACT_STATUS'] == 'Approved']
x[x['AMT_BALANCE'] b> 0]

In [98]:
_credit.head(50)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
584804,1489396,100006,-1,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
520387,1489396,100006,-2,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1347528,1489396,100006,-3,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1399895,1489396,100006,-4,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
655566,1489396,100006,-5,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1636141,1489396,100006,-6,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
2739019,1843384,100011,-2,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3496910,1843384,100011,-3,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
51047,1843384,100011,-4,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2674883,1843384,100011,-5,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
131693,1843384,100011,-6,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3637571,1843384,100011,-7,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2684587,1843384,100011,-8,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2084906,1843384,100011,-9,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
1017632,1843384,100011,-10,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3008205,1843384,100011,-11,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2081216,1843384,100011,-12,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2694047,1843384,100011,-13,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
234045,1843384,100011,-14,0.000,90000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
491629,1843384,100011,-15,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3795406,1843384,100011,-16,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3258036,1843384,100011,-17,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
171273,1843384,100011,-18,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
862440,1843384,100011,-19,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
1558584,1843384,100011,-20,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2574238,1843384,100011,-21,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2989414,1843384,100011,-22,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
1991199,1843384,100011,-23,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
385194,1843384,100011,-24,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2140005,1843384,100011,-25,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
1657673,1843384,100011,-26,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2554314,1843384,100011,-27,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2292821,1843384,100011,-28,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
1733625,1843384,100011,-29,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
388643,1843384,100011,-30,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3201936,1843384,100011,-31,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3164236,1843384,100011,-32,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2175132,1843384,100011,-33,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3396279,1843384,100011,-34,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3582868,1843384,100011,-35,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
3212587,1843384,100011,-36,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2771280,1843384,100011,-37,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
2297286,1843384,100011,-38,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Active,0,0
941947,1843384,100011,-39,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-563.355,-563.355,0.0,0,0.0,0.0,33.0,Active,0,0
3727775,1843384,100011,-40,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-563.355,-563.355,0.0,0,0.0,0.0,33.0,Active,0,0
3437370,1843384,100011,-41,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-563.355,-563.355,0.0,0,0.0,0.0,33.0,Active,0,0
1130968,1843384,100011,-42,0.000,180000,0.0,0.0,0.0,0.0,804.195,...,-563.355,-563.355,0.0,0,0.0,0.0,33.0,Active,0,0
184429,1843384,100011,-43,804.195,180000,0.0,0.0,0.0,0.0,9000.000,...,-563.355,-563.355,0.0,0,0.0,0.0,32.0,Active,0,0
1061617,1843384,100011,-44,54117.450,180000,0.0,0.0,0.0,0.0,9000.000,...,54117.450,54117.450,0.0,0,0.0,0.0,31.0,Active,0,0
3681627,1843384,100011,-45,59544.765,180000,0.0,0.0,0.0,0.0,9000.000,...,59544.765,59544.765,0.0,0,0.0,0.0,30.0,Active,0,0

In [99]:
credit_card_balance.columns.values

array(['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE',
       'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT',
       'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT',
       'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY',
       'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT',
       'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE',
       'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT',
       'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT',
       'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD',
       'SK_DPD_DEF'], dtype=object)

In [114]:
_d = credit_card_balance[credit_card_balance['AMT_DRAWINGS_ATM_CURRENT']+ credit_card_balance['AMT_DRAWINGS_OTHER_CURRENT']+credit_card_balance['AMT_DRAWINGS_POS_CURRENT'] > credit_card_balance['AMT_DRAWINGS_CURRENT']]

In [115]:
_d.shape

(2565, 23)

In [117]:
_g = credit_card_balance[credit_card_balance['AMT_DRAWINGS_ATM_CURRENT']+ credit_card_balance['AMT_DRAWINGS_OTHER_CURRENT']+credit_card_balance['AMT_DRAWINGS_POS_CURRENT'] <= credit_card_balance['AMT_DRAWINGS_CURRENT']]

In [119]:
_g.shape

(3087931, 23)

In [102]:
_x = credit_card_balance[credit_card_balance['AMT_RECIVABLE'] <= credit_card_balance['AMT_TOTAL_RECEIVABLE']]

In [104]:
_x.shape
credit_card_balance.shape

(3840312, 23)

In [108]:
null_pct = credit_card_balance.isnull().sum()/len(credit_card_balance)

In [109]:
null_pct

SK_ID_PREV                    0.000000
SK_ID_CURR                    0.000000
MONTHS_BALANCE                0.000000
AMT_BALANCE                   0.000000
AMT_CREDIT_LIMIT_ACTUAL       0.000000
AMT_DRAWINGS_ATM_CURRENT      0.195249
AMT_DRAWINGS_CURRENT          0.000000
AMT_DRAWINGS_OTHER_CURRENT    0.195249
AMT_DRAWINGS_POS_CURRENT      0.195249
AMT_INST_MIN_REGULARITY       0.079482
AMT_PAYMENT_CURRENT           0.199981
AMT_PAYMENT_TOTAL_CURRENT     0.000000
AMT_RECEIVABLE_PRINCIPAL      0.000000
AMT_RECIVABLE                 0.000000
AMT_TOTAL_RECEIVABLE          0.000000
CNT_DRAWINGS_ATM_CURRENT      0.195249
CNT_DRAWINGS_CURRENT          0.000000
CNT_DRAWINGS_OTHER_CURRENT    0.195249
CNT_DRAWINGS_POS_CURRENT      0.195249
CNT_INSTALMENT_MATURE_CUM     0.079482
NAME_CONTRACT_STATUS          0.000000
SK_DPD                        0.000000
SK_DPD_DEF                    0.000000
dtype: float64

In [148]:
_pay = credit_card_balance[credit_card_balance['AMT_DRAWINGS_CURRENT'] <= credit_card_balance['AMT_PAYMENT_TOTAL_CURRENT']]

In [149]:
_pay.shape

(3467090, 23)

In [130]:
_pay.shape

(2898162, 23)

In [141]:
np.nan * 1

nan

In [139]:
_g = credit_card_balance[credit_card_balance['MONTHS_BALANCE']< -12]

In [140]:
_g.shape

(2772456, 23)

In [142]:
sum([np.nan,1,2,3,4])

nan

In [145]:
38*0.8

30.400000000000002

In [154]:
_pay = credit_card_balance[credit_card_balance['AMT_INST_MIN_REGULARITY'] <= credit_card_balance['AMT_DRAWINGS_CURRENT']]

In [155]:
_pay.shape

(2258266, 23)

In [156]:
previous_application.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [157]:
previous_application.columns.values

array(['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY',
       'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT',
       'AMT_GOODS_PRICE', 'WEEKDAY_APPR_PROCESS_START',
       'HOUR_APPR_PROCESS_START', 'FLAG_LAST_APPL_PER_CONTRACT',
       'NFLAG_LAST_APPL_IN_DAY', 'RATE_DOWN_PAYMENT',
       'RATE_INTEREST_PRIMARY', 'RATE_INTEREST_PRIVILEGED',
       'NAME_CASH_LOAN_PURPOSE', 'NAME_CONTRACT_STATUS', 'DAYS_DECISION',
       'NAME_PAYMENT_TYPE', 'CODE_REJECT_REASON', 'NAME_TYPE_SUITE',
       'NAME_CLIENT_TYPE', 'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO',
       'NAME_PRODUCT_TYPE', 'CHANNEL_TYPE', 'SELLERPLACE_AREA',
       'NAME_SELLER_INDUSTRY', 'CNT_PAYMENT', 'NAME_YIELD_GROUP',
       'PRODUCT_COMBINATION', 'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE',
       'DAYS_LAST_DUE_1ST_VERSION', 'DAYS_LAST_DUE', 'DAYS_TERMINATION',
       'NFLAG_INSURED_ON_APPROVAL'], dtype=object)

In [188]:
null_pct = previous_application.isnull().sum()/len(previous_application)

In [189]:
null_pct

SK_ID_PREV                     0.000000e+00
SK_ID_CURR                     0.000000e+00
NAME_CONTRACT_TYPE             0.000000e+00
AMT_ANNUITY                    2.228667e-01
AMT_APPLICATION                0.000000e+00
AMT_CREDIT                     5.987257e-07
AMT_DOWN_PAYMENT               5.363648e-01
AMT_GOODS_PRICE                2.308177e-01
WEEKDAY_APPR_PROCESS_START     0.000000e+00
HOUR_APPR_PROCESS_START        0.000000e+00
FLAG_LAST_APPL_PER_CONTRACT    0.000000e+00
NFLAG_LAST_APPL_IN_DAY         0.000000e+00
RATE_DOWN_PAYMENT              5.363648e-01
RATE_INTEREST_PRIMARY          9.964370e-01
RATE_INTEREST_PRIVILEGED       9.964370e-01
NAME_CASH_LOAN_PURPOSE         0.000000e+00
NAME_CONTRACT_STATUS           0.000000e+00
DAYS_DECISION                  0.000000e+00
NAME_PAYMENT_TYPE              0.000000e+00
CODE_REJECT_REASON             0.000000e+00
NAME_TYPE_SUITE                4.911975e-01
NAME_CLIENT_TYPE               0.000000e+00
NAME_GOODS_CATEGORY            0.000000e+00
NAME_PORTFOLIO                 0.000000e+00
NAME_PRODUCT_TYPE              0.000000e+00
CHANNEL_TYPE                   0.000000e+00
SELLERPLACE_AREA               0.000000e+00
NAME_SELLER_INDUSTRY           0.000000e+00
CNT_PAYMENT                    2.228637e-01
NAME_YIELD_GROUP               0.000000e+00
PRODUCT_COMBINATION            2.071591e-04
DAYS_FIRST_DRAWING             4.029813e-01
DAYS_FIRST_DUE                 4.029813e-01
DAYS_LAST_DUE_1ST_VERSION      4.029813e-01
DAYS_LAST_DUE                  4.029813e-01
DAYS_TERMINATION               4.029813e-01
NFLAG_INSURED_ON_APPROVAL      4.029813e-01
dtype: float64

In [161]:
previous_application.isnull().any()

SK_ID_PREV                     False
SK_ID_CURR                     False
NAME_CONTRACT_TYPE             False
AMT_ANNUITY                     True
AMT_APPLICATION                False
AMT_CREDIT                      True
AMT_DOWN_PAYMENT                True
AMT_GOODS_PRICE                 True
WEEKDAY_APPR_PROCESS_START     False
HOUR_APPR_PROCESS_START        False
FLAG_LAST_APPL_PER_CONTRACT    False
NFLAG_LAST_APPL_IN_DAY         False
RATE_DOWN_PAYMENT               True
RATE_INTEREST_PRIMARY           True
RATE_INTEREST_PRIVILEGED        True
NAME_CASH_LOAN_PURPOSE         False
NAME_CONTRACT_STATUS           False
DAYS_DECISION                  False
NAME_PAYMENT_TYPE              False
CODE_REJECT_REASON             False
NAME_TYPE_SUITE                 True
NAME_CLIENT_TYPE               False
NAME_GOODS_CATEGORY            False
NAME_PORTFOLIO                 False
NAME_PRODUCT_TYPE              False
CHANNEL_TYPE                   False
SELLERPLACE_AREA               False
NAME_SELLER_INDUSTRY           False
CNT_PAYMENT                     True
NAME_YIELD_GROUP               False
PRODUCT_COMBINATION             True
DAYS_FIRST_DRAWING              True
DAYS_FIRST_DUE                  True
DAYS_LAST_DUE_1ST_VERSION       True
DAYS_LAST_DUE                   True
DAYS_TERMINATION                True
NFLAG_INSURED_ON_APPROVAL       True
dtype: bool

In [162]:
previous_application['AMT_DOWN_PAYMENT']

0              0.0
1              NaN
2              NaN
3              NaN
4              NaN
5              NaN
6              NaN
7              NaN
8              NaN
9              NaN
10             NaN
11             NaN
12             NaN
13             0.0
14             0.0
15         12649.5
16          1350.0
17             NaN
18             NaN
19             NaN
20             NaN
21             NaN
22             NaN
23             NaN
24             NaN
25             NaN
26             NaN
27             0.0
28          9000.0
29             NaN
            ...
1670184        NaN
1670185        NaN
1670186        NaN
1670187        NaN
1670188        NaN
1670189        NaN
1670190        NaN
1670191        NaN
1670192        NaN
1670193        NaN
1670194        NaN
1670195    24853.5
1670196        0.0
1670197        0.0
1670198     2290.5
1670199        0.0
1670200        0.0
1670201     2295.0
1670202        0.0
1670203        0.0
1670204        NaN
1670205        NaN
1670206        0.0
1670207        0.0
1670208        NaN
1670209        0.0
1670210    29250.0
1670211    10525.5
1670212        NaN
1670213        NaN
Name: AMT_DOWN_PAYMENT, Length: 1670214, dtype: float64

In [163]:
prev_currid = set(previous_application['SK_ID_CURR'])

In [166]:
currid =  set(train['SK_ID_CURR'])

In [167]:
len(currid - prev_currid)/len(currid)

0.05350702901684818

In [169]:
_RATE = previous_application[previous_application['AMT_DOWN_PAYMENT']/previous_application['AMT_GOODS_PRICE'] == previous_application['RATE_DOWN_PAYMENT']]

In [175]:
_RATE.shape

(370041, 37)

In [171]:
down_payment_len = previous_application['AMT_DOWN_PAYMENT'].isnull().sum()

In [172]:
down_payment_len

895844

In [173]:
previous_application.shape

(1670214, 37)

In [176]:
370041/1670214

0.22155304649583826

In [183]:
previous_application[previous_application['RATE_INTEREST_PRIMARY'] > previous_application['RATE_INTEREST_PRIVILEGED']].shape

(127, 37)

In [184]:
(previous_application['RATE_INTEREST_PRIMARY'].isnull() & previous_application['RATE_INTEREST_PRIMARY'].isnull()).sum()

1664263

In [185]:
(False & False)

False

In [187]:
previous_application['RATE_INTEREST_PRIMARY'].isnull().sum()/len(previous_application)

0.99643698352426691

In [190]:
set(previous_application['CODE_REJECT_REASON'])

{'CLIENT', 'HC', 'LIMIT', 'SCO', 'SCOFR', 'SYSTEM', 'VERIF', 'XAP', 'XNA'}