In [1]:
import pandas as pd
PATH = '/home/kai/data/kaggle/homecredit/'

x = pd.read_pickle(PATH + 'train_bo2.pkl')
train = pd.read_csv(PATH + 'application_train.csv')

In [2]:
categorical_feats = ['FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
                     'NAME_FAMILY_STATUS','NAME_HOUSING_TYPE','CODE_GENDER','EMERGENCYSTATE_MODE','FLAG_OWN_CAR',
                     'FLAG_OWN_REALTY','FONDKAPREMONT_MODE','HOUR_APPR_PROCESS_START','HOUSETYPE_MODE',
                     'NAME_CONTRACT_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 
                     'NAME_INCOME_TYPE', 'NAME_TYPE_SUITE', 'OCCUPATION_TYPE', 'ORGANIZATION_TYPE', 'WALLSMATERIAL_MODE',
                     'WEEKDAY_APPR_PROCESS_START','OCCUPATION_TYPE','FLAG_DOCUMENT_2','FLAG_DOCUMENT_3','FLAG_DOCUMENT_4',
                     'FLAG_DOCUMENT_5','FLAG_DOCUMENT_6','FLAG_DOCUMENT_7','FLAG_DOCUMENT_8','FLAG_DOCUMENT_9',
                     'FLAG_DOCUMENT_10','FLAG_DOCUMENT_11','FLAG_DOCUMENT_12','FLAG_DOCUMENT_13','FLAG_DOCUMENT_14',
                     'FLAG_DOCUMENT_15','FLAG_DOCUMENT_16','FLAG_DOCUMENT_17','FLAG_DOCUMENT_18','FLAG_DOCUMENT_19',
                     'FLAG_DOCUMENT_20','FLAG_DOCUMENT_21','NAME_TYPE_SUITE']

In [4]:
non_obj_categoricals = [
    'FONDKAPREMONT_MODE', 'HOUR_APPR_PROCESS_START', 'HOUSETYPE_MODE',
    'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
    'NAME_INCOME_TYPE', 'NAME_TYPE_SUITE', 'OCCUPATION_TYPE',
    'ORGANIZATION_TYPE', 'STATUS',
    'WALLSMATERIAL_MODE', 'WEEKDAY_APPR_PROCESS_START',
    'NAME_CASH_LOAN_PURPOSE', 'NAME_CONTRACT_STATUS', 
    'NAME_PAYMENT_TYPE', 'CODE_REJECT_REASON', 
    'NAME_CLIENT_TYPE', 'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 
    'NAME_PRODUCT_TYPE', 'CHANNEL_TYPE', 'NAME_SELLER_INDUSTRY', 
    'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION' 
]
a = non_obj_categoricals + [x for x in train.columns if train[x].dtype=='object']
a

['FONDKAPREMONT_MODE',
 'HOUR_APPR_PROCESS_START',
 'HOUSETYPE_MODE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'NAME_INCOME_TYPE',
 'NAME_TYPE_SUITE',
 'OCCUPATION_TYPE',
 'ORGANIZATION_TYPE',
 'STATUS',
 'WALLSMATERIAL_MODE',
 'WEEKDAY_APPR_PROCESS_START',
 'NAME_CONTRACT_TYPE_BAVG',
 'NAME_CASH_LOAN_PURPOSE',
 'NAME_CONTRACT_STATUS',
 'NAME_PAYMENT_TYPE',
 'CODE_REJECT_REASON',
 'NAME_CLIENT_TYPE',
 'NAME_GOODS_CATEGORY',
 'NAME_PORTFOLIO',
 'NAME_PRODUCT_TYPE',
 'CHANNEL_TYPE',
 'NAME_SELLER_INDUSTRY',
 'NAME_YIELD_GROUP',
 'PRODUCT_COMBINATION',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'OCCUPATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'ORGANIZATION_TYPE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE']

In [38]:
l = list(set(a) - set(categorical_feats))
k = [m for m in l if m not in x.columns]
set(a) - set(k)

{'CODE_GENDER',
 'EMERGENCYSTATE_MODE',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'FONDKAPREMONT_MODE',
 'HOUR_APPR_PROCESS_START',
 'HOUSETYPE_MODE',
 'NAME_CONTRACT_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'NAME_INCOME_TYPE',
 'NAME_TYPE_SUITE',
 'OCCUPATION_TYPE',
 'ORGANIZATION_TYPE',
 'WALLSMATERIAL_MODE',
 'WEEKDAY_APPR_PROCESS_START'}

In [40]:
x[['CODE_GENDER',
 'EMERGENCYSTATE_MODE',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'FONDKAPREMONT_MODE',
 'HOUR_APPR_PROCESS_START',
 'HOUSETYPE_MODE',
 'NAME_CONTRACT_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'NAME_INCOME_TYPE',
 'NAME_TYPE_SUITE',
 'OCCUPATION_TYPE',
 'ORGANIZATION_TYPE',
 'WALLSMATERIAL_MODE',
 'WEEKDAY_APPR_PROCESS_START']]

,CODE_GENDER,EMERGENCYSTATE_MODE,FLAG_OWN_CAR,FLAG_OWN_REALTY,FONDKAPREMONT_MODE,HOUR_APPR_PROCESS_START,HOUSETYPE_MODE,NAME_CONTRACT_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,NAME_INCOME_TYPE,NAME_TYPE_SUITE,OCCUPATION_TYPE,ORGANIZATION_TYPE,WALLSMATERIAL_MODE,WEEKDAY_APPR_PROCESS_START
0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,11,0,0,1,1,0,1,1,1,1,1,1
2,0,-1,1,0,-1,9,-1,1,0,0,0,0,0,0,2,-1,1
3,1,-1,0,0,-1,17,-1,0,0,2,0,0,0,0,0,-1,0
4,0,-1,0,0,-1,11,-1,0,0,0,0,0,0,1,3,-1,2
5,0,-1,0,0,-1,16,-1,0,0,1,0,1,2,0,4,-1,0
6,1,-1,1,0,-1,16,-1,0,1,1,0,2,0,2,0,-1,3
7,0,-1,1,0,-1,16,-1,0,1,1,0,1,0,3,4,-1,1
8,1,-1,0,0,-1,14,-1,0,0,1,0,3,3,-1,5,-1,0
9,0,-1,0,0,-1,8,-1,1,0,0,0,0,0,0,6,-1,2
10,1,-1,0,0,-1,15,-1,0,1,1,0,0,0,1,7,-1,4
11,1,-1,0,0,-1,7,-1,0,0,1,0,3,3,-1,5,-1,5
12,1,0,0,0,0,10,0,0,0,1,0,0,0,0,8,-1,5
13,0,0,1,1,0,13,0,0,0,1,0,0,0,4,9,2,2
14,1,0,0,0,0,9,0,0,0,1,0,0,0,0,10,2,1
15,0,-1,1,0,-1,6,-1,0,0,0,1,0,1,0,8,-1,4
16,0,-1,0,1,-1,12,-1,0,0,1,0,0,0,4,2,-1,2
17,1,-1,0,0,-1,10,-1,1,0,1,0,0,0,0,11,-1,1
18,1,0,0,0,0,13,0,1,0,3,0,0,4,0,12,0,5
19,1,-1,0,0,-1,12,-1,0,1,0,0,1,0,1,13,-1,1
20,0,0,1,0,0,13,0,1,0,1,0,0,0,0,9,0,5
21,1,-1,1,0,-1,9,-1,0,0,1,0,2,0,5,14,-1,1
22,1,0,0,1,0,6,0,0,0,1,1,0,0,5,9,2,2
23,1,0,0,0,1,12,0,0,0,1,0,3,0,-1,5,3,5
24,0,0,1,1,0,14,0,0,0,1,0,0,0,4,0,2,2
25,1,0,0,0,0,8,0,0,0,1,0,0,0,6,0,0,4
26,1,1,0,0,-1,9,0,0,0,3,0,0,0,7,0,4,1
27,0,-1,0,0,-1,10,-1,0,0,1,0,0,1,0,15,-1,4
28,0,-1,1,0,-1,11,-1,0,1,0,0,1,0,-1,16,-1,0
29,0,0,0,0,0,16,0,1,1,0,2,0,0,0,0,2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,0,-1,0,0,-1,15,-1,0,0,1,0,0,1,3,0,-1,5
307482,1,0,1,0,3,15,0,0,0,1,0,2,0,3,54,1,2
307483,1,0,0,0,0,12,0,0,0,4,0,3,0,-1,5,0,1
307484,1,-1,1,1,-1,13,-1,0,0,1,1,2,0,3,0,-1,1
307485,1,-1,0,0,-1,18,-1,1,0,4,2,0,1,5,0,-1,4
307486,1,0,1,0,-1,17,0,0,1,2,0,2,0,-1,8,2,4
307487,0,-1,0,0,-1,10,-1,0,0,1,0,3,0,-1,5,-1,0
307488,1,0,0,1,-1,18,-1,0,1,0,0,1,0,1,2,-1,0
307489,1,1,0,0,0,5,0,0,0,2,0,2,0,5,0,0,5
307490,0,-1,0,0,-1,12,-1,0,1,0,0,2,0,0,27,-1,4
307491,0,-1,1,0,-1,10,-1,0,0,1,0,2,0,4,9,-1,4
307492,0,-1,1,0,-1,10,-1,0,0,1,0,0,0,5,9,-1,5
307493,1,-1,0,0,-1,12,-1,0,0,1,0,0,0,10,1,-1,1
307494,0,-1,1,1,-1,9,-1,0,0,1,0,2,1,4,9,-1,1
307495,0,0,1,1,1,14,0,0,1,1,0,0,0,11,0,2,0
307496,1,-1,0,1,-1,13,-1,1,1,1,0,0,1,7,9,-1,2
307497,1,-1,1,0,-1,13,-1,0,0,1,0,0,0,5,14,-1,2
307498,0,0,1,0,-1,10,0,0,0,1,0,2,0,0,11,2,1
307499,1,-1,0,0,-1,15,-1,0,0,1,0,2,0,9,7,-1,6
307500,1,0,0,0,-1,10,0,0,1,1,0,0,0,-1,0,2,5
307501,1,0,0,0,-1,14,0,0,0,1,0,2,0,13,20,0,0
307502,1,-1,0,0,-1,16,-1,0,0,1,0,0,0,0,1,-1,1
307503,1,-1,0,0,-1,11,-1,0,1,0,0,2,0,1,37,-1,4
307504,1,-1,0,0,-1,11,-1,0,0,4,0,0,0,5,9,-1,0
307505,1,0,0,0,0,15,0,0,0,0,0,3,0,-1,5,2,1
307506,0,0,0,1,0,15,0,0,0,4,2,0,0,5,17,0,2
307507,1,0,0,0,0,8,0,0,0,3,0,3,0,-1,5,0,1
307508,1,0,0,0,0,9,0,0,1,4,0,0,0,3,1,2,2
307509,1,0,0,0,-1,9,0,0,0,1,0,2,0,0,27,0,0
307510,1,0,0,1,-1,20,0,0,1,1,0,2,0,0,0,2,2