In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
df = pd.read_csv('ratio_stand.csv')
print(df.shape)

(369, 10)

In [3]:
# devided by actual std
df['catNorm1'] = df['catBoostEncoRMSE'] / df['val_std']

df['catNorm2'] = df['catBoostEncoRMSE'] / df['preds_std']

In [4]:
selected_col = ['colName','catBoostEncoRMSE','meByCatRatio','corr','catNorm1','catNorm2']
df[selected_col]

,colName,catBoostEncoRMSE,meByCatRatio,corr,catNorm1,catNorm2
0,DAYS_LAST_PHONE_CHANGE_x,2.852335e+01,29.318479,0.999418,0.034109,0.034126
1,NAME_FAMILY_STATUS_NAME_EDUCATION_TYPE_AMT_INC...,8.764916e+04,85.759199,0.999932,0.011661,0.011662
2,AMT_INCOME_TOTAL_divide_DAYS_EMPLOYED,4.475888e+02,1.257623,0.611131,0.795196,1.486291
3,NAME_FAMILY_STATUS_NAME_EDUCATION_TYPE_DAYS_BI...,5.347836e+01,41.396058,0.999708,0.024157,0.024174
4,NAME_FAMILY_STATUS_NAME_EDUCATION_TYPE_AMT_CRE...,1.602886e+04,38.723005,0.999667,0.025825,0.025837
5,DAYS_LAST_PHONE_CHANGE_divide_DAYS_EMPLOYED,1.027123e+01,1.045913,0.304169,0.956113,4.294476
6,NAME_EDUCATION_TYPE_CODE_GENDER_DAYS_REGISTRAT...,6.052282e+01,32.632567,0.999530,0.030645,0.030676
7,NAME_EDUCATION_TYPE_CODE_GENDER_DAYS_REGISTRAT...,8.895948e+01,43.094936,0.999731,0.023205,0.023209
8,NAME_EDUCATION_TYPE_CODE_GENDER_DAYS_BIRTH_mea...,4.184491e+01,53.391773,0.999825,0.018730,0.018731
9,NAME_EDUCATION_TYPE_CODE_GENDER_DAYS_ID_PUBLIS...,1.583208e+01,47.077842,0.999774,0.021241,0.021250
10,NAME_EDUCATION_TYPE_CODE_GENDER_REGION_POPULAT...,6.457799e-05,143.433160,0.999976,0.006972,0.006973
11,NAME_FAMILY_STATUS_CODE_GENDER_AMT_CREDIT_max_...,1.426213e+04,40.302569,0.999692,0.024813,0.024816
12,NAME_FAMILY_STATUS_CODE_GENDER_AMT_INCOME_TOTA...,6.057006e+05,10.675278,0.995603,0.093673,0.094142
13,NAME_FAMILY_STATUS_CODE_GENDER_DAYS_REGISTRATI...,8.072044e+01,49.839007,0.999799,0.020065,0.020068
14,DAYS_LAST_PHONE_CHANGE_divide_DAYS_ID_PUBLISH,1.710353e+01,1.478721,0.749518,0.676265,1.106227
15,AMT_INCOME_TOTAL_divide_AMT_ANNUITY,2.016228e+00,2.504366,0.919650,0.399307,0.471118
16,annuity_income_percentage,2.963960e-03,31.694678,0.999502,0.031551,0.031556
17,AMT_ANNUITY_x,4.288698e+02,33.749046,0.999561,0.029631,0.029643
18,AMT_CREDIT_divide_AMT_ANNUITY,2.988538e-01,26.056175,0.999263,0.038379,0.038422
19,NAME_FAMILY_STATUS_NAME_EDUCATION_TYPE_AMT_ANN...,5.999771e+02,71.603802,0.999902,0.013966,0.013970
20,AMT_ANNUITY_divide_DAYS_EMPLOYED,2.143344e+02,1.058017,0.328922,0.945168,3.260761
21,NAME_EDUCATION_TYPE_CODE_GENDER_AMT_ANNUITY_me...,2.260413e+02,42.892306,0.999730,0.023315,0.023278
22,NAME_EDUCATION_TYPE_CODE_GENDER_AMT_ANNUITY_ma...,4.241137e+02,76.456723,0.999914,0.013080,0.013080
23,NAME_FAMILY_STATUS_CODE_GENDER_AMT_ANNUITY_max...,5.426343e+02,52.099531,0.999816,0.019195,0.019190
24,AMT_ANNUITY_divide_DAYS_ID_PUBLISH,4.582215e+02,1.321466,0.655717,0.756738,1.251731
25,DAYS_LAST_PHONE_CHANGE_divide_DAYS_REGISTRATION,1.631106e+01,1.477632,0.736438,0.676767,0.942679
26,AMT_ANNUITY_divide_DAYS_REGISTRATION,6.506781e+02,1.236737,0.588986,0.808582,1.313787
27,Wei_external_sources_max==DEVIDE==AMT_CREDIT,6.580026e-08,24.941310,0.999196,0.040094,0.040160
28,external_sources_max,4.544953e-03,34.289586,0.999575,0.029165,0.029184
29,external_sources_min,4.239322e-03,43.926656,0.999741,0.022766,0.022774
...,...,...,...,...,...,...
339,NAME_EDUCATION_TYPE_CODE_GENDER_OWN_CAR_AGE_me...,8.613181e-02,106.927510,0.999956,0.009352,0.009351
340,OWN_CAR_AGE_divide_DAYS_ID_PUBLISH,2.869608e-01,1.454123,0.735202,0.687749,1.111125
341,OWN_CAR_AGE_divide_DAYS_REGISTRATION,1.638066e-01,1.472350,0.735338,0.679239,0.872333
342,AMT_INCOME_TOTAL_divide_OWN_CAR_AGE,6.941984e+03,9.251363,0.994141,0.108097,0.108770
343,REFUSED_DAYS_DECISION_MAX,1.720903e+02,4.301576,0.972629,0.232484,0.240565
344,REFUSED_AMT_APPLICATION_MIN,8.729888e+04,3.839988,0.965522,0.260418,0.271650
345,REFUSED_AMT_APPLICATION_MAX,9.015593e+04,5.380177,0.982577,0.185909,0.190021
346,REFUSED_DAYS_DECISION_MIN,2.270592e+02,3.616467,0.961024,0.276514,0.288424
347,REFUSED_APP_CREDIT_PERC_MIN,7.495700e-02,3.694275,0.962746,0.270703,0.284852
348,REFUSED_AMT_ANNUITY_MIN,4.704039e+03,3.197764,0.950337,0.312719,0.339961
349,OWN_CAR_AGE_divide_DAYS_LAST_PHONE_CHANGE,9.002738e-02,16.778334,0.998306,0.059604,0.060487
350,AMT_ANNUITY_divide_CNT_CHILDREN,4.167650e+02,34.633190,0.999584,0.028874,0.028916
351,creditcard_CNT_DRAWINGS_CURRENT_sum,1.302588e+01,3.915906,0.966847,0.255369,0.263730
352,creditcard_AMT_CREDIT_LIMIT_ACTUAL_divide_AMT_...,5.649690e+04,2.613313,0.924065,0.382657,0.420375
353,creditcard_AMT_DRAWINGS_CURRENT_divide_AMT_PAY...,4.808101e+03,1.995450,0.866266,0.501155,0.553433
354,creditcard_AMT_BALANCE_divide_AMT_PAYMENT_TOTA...,4.700795e+03,1.460463,0.730896,0.684788,1.013865
355,CC_CNT_DRAWINGS_CURRENT_VAR,3.265880e+01,2.310774,0.905112,0.432763,0.524865
356,credit_card_monthly_diff,7.948614e+03,1.866212,0.849508,0.536022,0.709754
357,creditcard_CNT_DRAWINGS_CURRENT_std,4.025274e-01,8.659468,0.993377,0.115482,0.117623
358,creditcard_AMT_DRAWINGS_CURRENT_divide_MONTHS_...,2.210400e+04,2.399281,0.909000,0.416811,0.457944
359,CC_AMT_DRAWINGS_ATM_CURRENT_MEAN,6.051734e+03,3.575489,0.960898,0.279688,0.303489
360,creditcard_CNT_DRAWINGS_ATM_CURRENT_mean,2.988997e-01,2.949557,0.941730,0.339078,0.377163
361,creditcard_AMT_PAYMENT_CURRENT_divide_AMT_RECI...,7.855512e+03,2.000413,0.866079,0.499935,0.580826
362,creditcard_AMT_BALANCE_divide_AMT_PAYMENT_CURR...,2.681035e+03,1.551178,0.764407,0.644752,0.842653
363,creditcard_AMT_BALANCE_divide_AMT_PAYMENT_CURR...,1.275238e+04,1.379072,0.691493,0.725173,1.154830
364,creditcard_AMT_PAYMENT_CURRENT_divide_CNT_DRAW...,1.038819e+04,1.763414,0.826066,0.567099,0.638193
365,creditcard_CNT_DRAWINGS_ATM_CURRENT_std,2.123270e-01,4.663596,0.976863,0.214435,0.216101
366,creditcard_AMT_BALANCE_divide_CNT_DRAWINGS_POS...,2.301074e+04,2.409442,0.909797,0.415056,0.456410
367,creditcard_AMT_DRAWINGS_CURRENT_divide_CNT_DRA...,1.200606e+04,2.634958,0.926817,0.379525,0.435244
368,CC_AMT_DRAWINGS_ATM_CURRENT_VAR,5.097971e+09,1.727389,0.824091,0.578911,0.821497

In [5]:
s = df[selected_col]
s.corr()

                  catBoostEncoRMSE  meByCatRatio      corr  catNorm1  catNorm2
catBoostEncoRMSE          1.000000     -0.030027 -0.157825 -0.001858 -0.002714
meByCatRatio             -0.030027      1.000000  0.282378 -0.032553 -0.030082
corr                     -0.157825      0.282378  1.000000 -0.238699 -0.228886
catNorm1                 -0.001858     -0.032553 -0.238699  1.000000 -0.002717
catNorm2                 -0.002714     -0.030082 -0.228886 -0.002717  1.000000

In [6]:
df[df['corr']>0.7].shape

(332, 12)

# LOAD FILEs

In [7]:
import sys
sys.path.append('../LIB/')
from env import ENV

train_ori = pd.read_pickle(ENV.lgb_train_0827.value)
print(train_ori.shape)
train_na = pd.read_pickle(ENV.lgb_train_0827_na_extrem.value)
print(train_na.shape)
test_ori = pd.read_pickle(ENV.lgb_test_0827.value)
print(test_ori.shape)
test_na = pd.read_pickle(ENV.lgb_test_0827_na_extrem.value)
print(test_na.shape)

(307511, 409)
(307511, 369)
(48744, 408)
(48744, 369)

In [ ]:
train_ori.to_pickle(ENV.lgb_train_0827.value)
test_ori.to_pickle(ENV.lgb_test_0827.value)
train_na.to_pickle(ENV.lgb_train_0827_na_extrem.value)
test_na.to_pickle(ENV.lgb_test_0827_na_extrem.value)

In [8]:
train_save = train_ori.copy()
test_save = test_ori.copy()

## Save By MyRatio

In [34]:
threds = 35
col = 'meByCatRatio'
df_selected = df[df[col] > threds].copy()
print(df_selected.shape)
selected_col = list(df_selected['colName'].values)
prefix = col + '_' + str(threds)+'colNUM_'+str(len(selected_col))

(25, 12)

In [35]:
train_save_name = '../../data/fill_na_410/train_{}.pkl'.format(prefix)
test_save_name = '../../data/fill_na_410/test_{}.pkl'.format(prefix)
train_save = train_ori.copy()
test_save = test_ori.copy()
for col in tqdm(selected_col):
    train_save[col] = train_na[col].copy()
    test_save[col] = test_na[col].copy()
train_save.to_pickle(train_save_name)
print(train_save_name)
print(train_save.shape)
test_save.to_pickle(test_save_name)
print(test_save_name)
print(test_save.shape)

100%|██████████| 25/25 [00:00<00:00, 833.12it/s]

../../data/fill_na_410/train_meByCatRatio_35colNUM_25.pkl
(307511, 409)
../../data/fill_na_410/test_meByCatRatio_35colNUM_25.pkl
(48744, 408)

## Save By Corr

In [51]:
threds = 0.9999
col = 'corr'
df_selected = df[df[col] > threds].copy()
print(df_selected.shape)
selected_col = list(df_selected['colName'].values)
prefix = col + '_' + str(threds)+'colNUM_'+str(len(selected_col))

(9, 12)

In [52]:
train_save_name = '../../data/fill_na_410/train_{}.pkl'.format(prefix)
test_save_name = '../../data/fill_na_410/test_{}.pkl'.format(prefix)
train_save = train_ori.copy()
test_save = test_ori.copy()
for col in tqdm(selected_col):
    train_save[col] = train_na[col].copy()
    test_save[col] = test_na[col].copy()
train_save.to_pickle(train_save_name)
print(train_save_name)
print(train_save.shape)
test_save.to_pickle(test_save_name)
print(test_save_name)
print(test_save.shape)

100%|██████████| 9/9 [00:00<00:00, 584.53it/s]

../../data/fill_na_410/train_corr_0.9999colNUM_9.pkl
(307511, 409)
../../data/fill_na_410/test_corr_0.9999colNUM_9.pkl
(48744, 408)

## Save By Norm 1

In [61]:
threds = 0.03
col = 'catNorm1'
df_selected = df[df[col] < threds].copy()
print(df_selected.shape)
selected_col = list(df_selected['colName'].values)
prefix = col + '_' + str(threds)+'colNUM_'+str(len(selected_col))

(28, 12)

In [62]:
train_save_name = '../../data/fill_na_410/train_{}.pkl'.format(prefix)
test_save_name = '../../data/fill_na_410/test_{}.pkl'.format(prefix)
train_save = train_ori.copy()
test_save = test_ori.copy()
for col in tqdm(selected_col):
    train_save[col] = train_na[col].copy()
    test_save[col] = test_na[col].copy()
train_save.to_pickle(train_save_name)
print(train_save_name)
print(train_save.shape)
test_save.to_pickle(test_save_name)
print(test_save_name)
print(test_save.shape)

100%|██████████| 28/28 [00:00<00:00, 692.08it/s]

../../data/fill_na_410/train_catNorm1_0.03colNUM_28.pkl
(307511, 409)
../../data/fill_na_410/test_catNorm1_0.03colNUM_28.pkl
(48744, 408)

## Save By Norm 2

In [71]:
threds = 0.03
col = 'catNorm2'
df_selected = df[df[col] < threds].copy()
print(df_selected.shape)
selected_col = list(df_selected['colName'].values)
prefix = col + '_' + str(threds)+'colNUM_'+str(len(selected_col))

(28, 12)

In [72]:
train_save_name = '../../data/fill_na_410/train_{}.pkl'.format(prefix)
test_save_name = '../../data/fill_na_410/test_{}.pkl'.format(prefix)
train_save = train_ori.copy()
test_save = test_ori.copy()
for col in tqdm(selected_col):
    train_save[col] = train_na[col].copy()
    test_save[col] = test_na[col].copy()
train_save.to_pickle(train_save_name)
print(train_save_name)
print(train_save.shape)
test_save.to_pickle(test_save_name)
print(test_save_name)
print(test_save.shape)

100%|██████████| 28/28 [00:00<00:00, 700.96it/s]

../../data/fill_na_410/train_catNorm2_0.03colNUM_28.pkl
(307511, 409)
../../data/fill_na_410/test_catNorm2_0.03colNUM_28.pkl
(48744, 408)

In [99]:
t1 = pd.read_pickle(ENV.lgb_train_0827_na_extrem.value)
t2 = pd.read_pickle(ENV.lgb_test_0827_na_extrem.value)

In [100]:
t3 = pd.concat([t1,t2])

In [101]:
t2

       DAYS_LAST_PHONE_CHANGE_x
0                       -1740.0
1                           0.0
2                        -856.0
3                       -1805.0
4                        -821.0
5                       -1705.0
6                       -1182.0
7                       -1182.0
8                        -829.0
9                       -1423.0
10                      -1671.0
11                      -1097.0
12                       -619.0
13                      -1414.0
14                       -765.0
15                       -317.0
16                      -2154.0
17                      -1132.0
18                      -1616.0
19                       -814.0
20                      -2297.0
21                      -1144.0
22                       -519.0
23                      -1582.0
24                      -2470.0
25                          0.0
26                       -672.0
27                      -1792.0
28                      -2865.0
29                          0.0
...                         ...
48714                    -418.0
48715                    -695.0
48716                    -281.0
48717                   -2671.0
48718                   -1787.0
48719                   -1530.0
48720                   -1239.0
48721                    -554.0
48722                    -976.0
48723                    -911.0
48724                   -2019.0
48725                   -2067.0
48726                   -2010.0
48727                    -136.0
48728                    -761.0
48729                   -1415.0
48730                    -786.0
48731                    -399.0
48732                    -493.0
48733                   -1786.0
48734                    -655.0
48735                   -1707.0
48736                    -611.0
48737                   -1252.0
48738                    -987.0
48739                    -684.0
48740                       0.0
48741                    -838.0
48742                   -2308.0
48743                    -327.0

[48744 rows x 1 columns]

In [102]:
t1

        DAYS_LAST_PHONE_CHANGE_x
0                        -1134.0
1                         -828.0
2                         -815.0
3                         -617.0
4                        -1106.0
5                        -2536.0
6                        -1562.0
7                        -1070.0
8                            0.0
9                        -1673.0
10                        -844.0
11                       -2396.0
12                       -2370.0
13                          -4.0
14                        -188.0
15                        -925.0
16                          -3.0
17                       -2811.0
18                        -239.0
19                       -1850.0
20                        -296.0
21                           0.0
22                        -468.0
23                        -795.0
24                          -4.0
25                           0.0
26                        -161.0
27                          -2.0
28                        -849.0
29                        -599.0
...                          ...
307481                   -2941.0
307482                    -611.0
307483                   -1775.0
307484                   -1578.0
307485                    -336.0
307486                       0.0
307487                    -846.0
307488                    -610.0
307489                    -307.0
307490                    -439.0
307491                   -1357.0
307492                       0.0
307493                    -249.0
307494                    -367.0
307495                   -2919.0
307496                    -826.0
307497                   -1344.0
307498                    -734.0
307499                   -1511.0
307500                   -1459.0
307501                    -448.0
307502                   -1516.0
307503                   -2315.0
307504                       0.0
307505                       0.0
307506                    -273.0
307507                       0.0
307508                   -1909.0
307509                    -322.0
307510                    -787.0

[307511 rows x 1 columns]