In [1]:
import pandas as pd
import numpy as np

In [42]:
report = pd.read_csv('add_each_col_score_v3_.csv')

In [43]:
base = report[report.colName=='noadd'].iloc[0]
base_holdout_overall = base['holdout_overall']
base_cv_mean = base['val_mean']

In [44]:
available = report[(report.holdout_overall<base_holdout_overall)&(report.val_mean<base_cv_mean)]
available

Empty DataFrame
Columns: [colName, holdout_overall, holdout_mean, val_mean, train_mean]
Index: []

In [45]:
report.sort_values('holdout_overall')

,colName,holdout_overall,holdout_mean,val_mean,train_mean
0,noadd,0.426123,0.426745,0.416188,0.406268
169,model+city+creative_type+osv_count_in_previous...,0.426137,0.426734,0.416235,0.406783
201,app_id+advert_name+user_tags+osv_count_in_prev...,0.426160,0.426785,0.416260,0.406244
184,city+user_tags+creative_type+osv_count_in_next...,0.426163,0.426846,0.416207,0.405188
42,model+advert_name+user_tags+creative_type_coun...,0.426169,0.426806,0.416203,0.406047
59,model+advert_name+creative_type+osv_count_in_p...,0.426175,0.426799,0.416263,0.406189
187,app_id+city+advert_name+user_tags_count_in_nex...,0.426187,0.426787,0.416224,0.406808
143,city+advert_name+creative_type+osv_count_in_ne...,0.426189,0.426816,0.416297,0.406271
25,app_id+advert_name+user_tags+creative_type_cou...,0.426192,0.426903,0.416214,0.405001
31,app_id+city+advert_name+user_tags_count_in_nex...,0.426196,0.426854,0.416209,0.405731
129,city+user_tags+creative_type+osv_count_in_prev...,0.426200,0.426793,0.416235,0.406779
146,city+advert_name+user_tags+osv_count_in_next_n...,0.426212,0.426855,0.416234,0.405942
72,model+city+user_tags+osv_count_in_previous_n_t...,0.426212,0.426913,0.416240,0.405382
141,city+advert_name+user_tags+osv_count_in_next_n...,0.426213,0.426906,0.416252,0.405139
24,model+app_id+creative_type+osv_count_in_next_n...,0.426217,0.426874,0.416219,0.405819
18,model+city+user_tags+creative_type_count_in_ne...,0.426218,0.426862,0.416236,0.406221
65,city+advert_name+creative_type+osv_count_in_pr...,0.426224,0.426888,0.416228,0.405801
174,app_id+advert_name+creative_type+osv_count_in_...,0.426228,0.426843,0.416245,0.406409
87,model+city+advert_name+osv_count_in_next_n_tim...,0.426228,0.426853,0.416225,0.406314
205,city+advert_name+user_tags+creative_type_count...,0.426228,0.426845,0.416244,0.406500
203,model+app_id+city+user_tags_count_in_next_n_ti...,0.426229,0.426827,0.416250,0.406905
122,model+app_id+user_tags+osv_count_in_previous_n...,0.426229,0.426818,0.416223,0.407022
89,model+app_id+user_tags+creative_type_count_in_...,0.426229,0.426930,0.416212,0.405326
119,model+user_tags+creative_type+osv_count_in_pre...,0.426230,0.426923,0.416202,0.405476
99,model+city+user_tags+osv_count_in_next_n_time_...,0.426232,0.426886,0.416242,0.405984
147,model+app_id+advert_name+creative_type_count_i...,0.426232,0.426877,0.416248,0.405801
44,model+city+creative_type+osv_count_in_next_n_t...,0.426234,0.426859,0.416261,0.406543
57,model+app_id+advert_name+osv_count_in_previous...,0.426234,0.426852,0.416246,0.406304
132,model+city+advert_name+user_tags_count_in_next...,0.426236,0.426846,0.416191,0.406495
94,city+user_tags+creative_type+osv_count_in_next...,0.426236,0.426886,0.416244,0.405837
...,...,...,...,...,...
126,app_id+city+user_tags+creative_type_count_in_p...,0.426376,0.426991,0.416255,0.406515
160,model+city+advert_name+osv_count_in_next_n_tim...,0.426376,0.427003,0.416231,0.406116
144,app_id+advert_name+user_tags+osv_count_in_prev...,0.426380,0.427053,0.416283,0.405586
98,model+app_id+city+advert_name_count_in_previou...,0.426380,0.427033,0.416259,0.406031
134,app_id+advert_name+user_tags+creative_type_cou...,0.426381,0.427042,0.416248,0.405637
196,model+app_id+advert_name+user_tags_count_in_pr...,0.426382,0.427009,0.416222,0.406403
177,model+city+advert_name+creative_type_count_in_...,0.426383,0.427009,0.416235,0.406126
96,model+app_id+user_tags+creative_type_count_in_...,0.426383,0.427050,0.416283,0.405857
34,app_id+advert_name+creative_type+osv_count_in_...,0.426390,0.426999,0.416305,0.406045
151,app_id+advert_name+user_tags+osv_count_in_next...,0.426391,0.427058,0.416233,0.405667
17,model+app_id+user_tags+osv_count_in_next_n_tim...,0.426391,0.427034,0.416259,0.406137
103,model+app_id+city+creative_type_count_in_next_...,0.426391,0.427036,0.416196,0.406089
74,model+app_id+advert_name+user_tags_count_in_ne...,0.426392,0.427004,0.416226,0.406389
120,model+city+advert_name+creative_type_count_in_...,0.426394,0.427043,0.416230,0.406019
121,app_id+advert_name+creative_type+osv_count_in_...,0.426398,0.426985,0.416259,0.406638
53,app_id+user_tags+creative_type+osv_count_in_ne...,0.426399,0.427094,0.416298,0.405633
40,model+advert_name+creative_type+osv_count_in_p...,0.426400,0.427071,0.416291,0.406259
78,app_id+city+advert_name+creative_type_count_in...,0.426410,0.426985,0.416291,0.407160
190,app_id+user_tags+creative_type+osv_count_in_ne...,0.426412,0.427018,0.416262,0.406476
14,app_id+user_tags+creative_type+osv_count_in_pr...,0.426414,0.427035,0.416268,0.406353
38,model+app_id+user_tags+osv_count_in_next_n_tim...,0.426422,0.427064,0.416258,0.405891
62,model+advert_name+user_tags+creative_type_coun...,0.426423,0.427095,0.416203,0.405194
64,advert_name+user_tags+creative_type+osv_count_...,0.426426,0.427101,0.416246,0.405795
133,model+user_tags+creative_type+osv_count_in_nex...,0.426433,0.427085,0.416260,0.406060
173,app_id+advert_name+user_tags+osv_count_in_next...,0.426444,0.427048,0.416259,0.407086
109,advert_name+user_tags+creative_type+osv_count_...,0.426444,0.427101,0.416257,0.406211
33,advert_name+user_tags+creative_type+osv_count_...,0.426449,0.427082,0.416239,0.406481
106,app_id+advert_name+user_tags+creative_type_cou...,0.426480,0.427093,0.416274,0.406598
167,app_id+advert_name+user_tags+creative_type_cou...,0.426486,0.427135,0.416260,0.406242
30,model+app_id+advert_name+user_tags_count_in_ne...,0.426595,0.427265,0.416227,0.405538